#!/bin/sh
#############################################
## Start / Stop Script for OpenBSC ##
#############################################

SCRIPT_NAME="BTS"
HLR="/dev/shm/hlr.sqlite3"
OPENBSC="/home/OpenBSC/open-bsc.cfg"

#############################################
## Fin des variables ##
#############################################
usage() {
echo "---------------------------------------------------------------------"
echo "Usage: ${SCRIPT_NAME} (stop|start)"
echo "---------------------------------------------------------------------"
exit 2
}

if [ -z $1 ]; then
usage
fi

bts_start() {
echo "---------------------------------------------------------------------"
echo "Starting BTS..."
echo "---------------------------------------------------------------------"
echo "Starting OSMONITB..."
su root -c "screen -AmdS OSMONITB taskset 0x1 osmo-nitb -c ${OPENBSC} -l ${HLR} -P -m -C --debug=DRLL:DCC:DMM:DRR:DRSL:DNM"
sleep 1
echo "Starting Linux Call Router..."
su root -c "screen -AmdS LCR taskset 0x3 lcr start"
sleep 1
echo "---------------------------------------------------------------------"
echo "BTS STARTED"
echo "---------------------------------------------------------------------"
}

bts_stop() {
echo "---------------------------------------------------------------------"
echo "Stopping BTS..."
echo "---------------------------------------------------------------------"
echo "Stopping OSMONITB..."
su root -c "pkill osmo"
sleep 1
echo "Stopping Linux Call Router..."
su root -c "pkill lcr"
sleep 1
echo "---------------------------------------------------------------------"
echo "BTS STOPPED."
echo "---------------------------------------------------------------------"
}

case $1 in
stop)
bts_stop
;;
start)
bts_start
;;
*)
usage
esac

exit 0
